config/routes.rb
NewChebitRu::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :conferences, :only => [:index, :show]
  resources :presentations, :only => [:show, :index]

  root :to => "conferences#index"
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/conference.rb
# -*- coding: utf-8 -*-
class Conference < ActiveRecord::Base
  attr_accessible :description, :date_conference, :title, :image ,:anounce, :photo_content

  has_many :presentations, :dependent => :destroy

  scope :ordered, order('date_conference DESC')

  validates :title, :presence => true
  validates :date_conference, :presence => true
  validates :description, :presence => true

  mount_uploader :image, ImageUploader

  def passed?
    self.date_conference < Time.now
  end

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :author, :conference_id, :file, :file_name, :title, :content, :video_embed, :image

  mount_uploader :file, FileUploader
  mount_uploader :image, ImageUploader

  belongs_to :conference

  scope :ordered, order(:title)

  validates :conference, :presence => true
  validates :title, :presence => true, :presence => true
  validates :author, :presence => true
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/conferences_controller.rb
# -*- coding: utf-8 -*-
class ConferencesController < ApplicationController
  def index
    @anounce_conference = Conference.where(:anounce=>true).first
    @conferences = Conference.ordered
  end

  def show
    @conference = Conference.find(params[:id])
  end
end

app/controllers/presentations_controller.rb
# -*- coding: utf-8 -*-
class PresentationsController < ApplicationController
  def show
    @presentation = Presentation.find(params[:id])
  end

  def index
    @presentations = Presentation.ordered
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def fontello icon, size, custom_class = '' 
    content_tag :i, '', :class => "fontello-icon-#{icon} icon-size-#{size} #{custom_class}"
  end

  def title(page_title)
    content_for (:title) { page_title }
  end

  def yield_or_default(section, default = "")
    content_for?(section) ? content_for(section) : default
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/index.html.haml
.page-header
  %h1 Прошедшие события

%ul.thumbnails
  - @conferences.each do |c|
    %li.span4
      .caption
        %h3= link_to c.title, conference_path(c)
        %p
          %i.icon-calendar.icon-gray
          %small.muted= l c.date_conference
      .thumbnail
        = link_to conference_path(c) do
          = image_tag c.image.extra.url, :size => '300x200'
      .caption
        %p= c.description.html_safe
        .pull-right
          = link_to conference_path(c), :class => 'btn' do
            %i.icon-bullhorn
            Доклады (#{c.presentations.count})
        .clearfix


-#%hr

-#.container
  -#.row
    -#- @conferences.each do |c|
      -#.span6
        -#= c.photo_content.try :html_safe

-#%br
-#%br
%hr
-# = render :partial => 'layouts/disquss'

app/views/conferences/show.html.haml
= title "CHEBIT: #{@conference.title}"
.page-header
  %h1= @conference.title
  %small= l @conference.date_conference


- @conference.presentations.ordered.each do |p|
  = render 'presentations/presentation', :presentation => p

%hr


- if @conference.photo_content.present?
  = @conference.photo_content.html_safe

%hr

= render :partial => 'layouts/disquss'

app/views/layouts/_footer.html.haml
%footer#footer
  .container
    .row-fluid
      .span2
        = link_to root_url, {:class => "logo"} do
          =image_tag 'chebit_logo_white.png'

      .span10.rows
        .row-fluid
          %big.span2
            Контакты
          .span10
            = link_to 'Данил Письменный', 'http://dapi.ru/', :target => '_blank'
        .row-fluid
          %big.span2
            Партнёры
          .span10.logos
            =link_to 'http://www.ravidok.ru/', :target => '_blank', :rel => 'nofollow' do
              = image_tag "vidok.png"
            =link_to 'http://webatmosfera.ru/', :target => '_blank', :rel => 'nofollow' do
              = image_tag "webatmosfera.svg"
            =link_to 'http://www.avis-design.ru/', :target => '_blank', :rel => 'nofollow' do
              = image_tag "avis_design.gif"
        .row-fluid
          %big.span3
            Коллеги по цеху
          .span9
            = link_to 'Данил Письменный', 'http://dapi.ru/', :target => '_blank'

app/views/layouts/_header.html.haml
%header#header.navbar.navbar-static-top
  %nav.navbar-inner
    .container
      .row
        .span3
          = link_to root_path, {:class => "logo"} do
            = image_tag 'chebit_logo_white.png'
        %big.span5
          %span Свободная конференция
          веб-разработчиков
        .span4.pull-right
          %b Попросите рассказать
          о том,
          %br
          что вам интересно
          %br
          %br
          %b Сделайте доклад
          о том, что знаете вы

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar
  -#{:data => {:spy=>:affix, 'offset-top'=>60}}
  %nav.navbar-inner
    = render_navigation :expand_all => true, :renderer => :bootstrap

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield_or_default(:title, "CHEBIT - barcamp-конференция веб-разработчиков в Чебоксарах")
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => content_for?(:description) ? yield(:description) : "CHEBIT", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    -#= stylesheet_link_tag "mediaelementplayer.min.css"
    = javascript_include_tag "application"
    = javascript_include_tag "mediaelement-and-player.min.js"
    = javascript_include_tag "jquery.imagesloaded.min.js"
    = javascript_include_tag 'modernizr.min'
    = javascript_include_tag "https://raw.github.com/livereload/livereload-js/master/dist/livereload.js?host=127.0.0.1"
    = csrf_meta_tags
    = yield(:head)
%body{:class => "#{controller_name} #{action_name}"}
  #wrapper{:role => "main" }
    = render 'layouts/header'
    .container#top
      .row
        .hero-unit.span8
          %strong Название какой-то конференции
          %a.round{:href => ""} 
            %i.fontello-icon-link
        .span3.pull-right.video
          %a.btn.btn-warning{:href => ""} 
            %i.fontello-icon-play
          %br/ 
          %br/ 
          %a{:href => ""} 
            %b
              %span видео и презентации с выступлений 
              %i.fontello-icon-right-open-mini
        %p.span8 Медиатека докладов с мероприятия, прошедшего 23 февраля, в баре "Матрос"
      -#%ul.nav.nav-pills
        -#= active_link_to 'Доклады', presentations_path, :wrap_tag => :li
        -#= active_link_to 'Прошедшие события', conferences_path, :wrap_tag => :li
      -#= render 'layouts/navigation'
    .container#main
      .content
        .stripe.span12 Все мероприятия
        .news.pull-left
          .list.span8
            .row-fluid
              .span3 
                %img{:src => "/assets/chebit_logo_dark.jpg", :alt => ""}/ 
              .span8 
                %h2.orangeDark Конференция &laquo;Веб-разработка и котики 2013&raquo;
                %time{:datetime => ""} 
                  %i.fontello-icon-calendar 
                  %span 23.02.2013
                %p Дезинфекция битриксоидов. Быстро, дешево, конфиденциально. 
              %a.more.span1{:href => ""} 
                %i.fontello-icon-right-open-big
                %span посмотреть доклады
          %hr/

          .list.span8
            .row-fluid
              .span3 
                %img{:src => "/assets/chebit_logo_dark.jpg", :alt => ""}/ 
              .span8 
                %h2.orangeDark Конференция &laquo;Веб-разработка и котики 2013&raquo;
                %time{:datetime => ""} 
                  %i.fontello-icon-calendar 
                  %span 23.02.2013
                %p Дезинфекция битриксоидов. Быстро, дешево, конфиденциально. 
              %a.more.span1{:href => ""} 
                %i.fontello-icon-right-open-big
                %span посмотреть доклады
          %hr/

        -#%aside.span4
        -#  %h3 

        =render_cell :twitter, :show
        
        .clearfix
        .center
          = render 'layouts/messages'
          = yield
  = render 'layouts/footer'

app/views/presentations/_presentation.html.haml
- present = presentation

.media
  .pull-left
    = link_to present do
      = image_tag present.image.thumb.url, :class => 'media-object', :size => '64x64'
  .media-body
    %h4.media-heading= link_to present.title, present
    .media-author
      %i.icon-user.icon-gray
      %small.muted= present.author
    %p= present.content.html_safe

    - if present.file.present?
      %p
        %i.fontello-icon-doc-text-inv.icon-size-16.v-align-top
        = link_to present.file_name, present.file.url

app/views/presentations/index.html.haml
- @presentations.each do |p|
  = render 'presentations/presentation', :presentation => p

app/views/presentations/show.html.haml
= title "CHEBIT - #{@presentation.title}"
.row
  .span12
    .row-fluid.row-presentation
      .span1
        .row-fluid
          .gray-block-title
            - if @presentation.video_embed.present?
              %i.fontello-icon-video.icon-size-32.gray-icon
            - if @presentation.file.present? && !@presentation.video_embed.present?
              %i.fontello-icon-doc-text-inv.icon-size-32.gray-icon
      .span7
        .row-fluid
          .gray-title
            = @presentation.title
      .span4
        .gray-block-author
          %i.fontello-icon-user.icon-size-16.v-align-top
          = @presentation.author
  .span12
    .row
      .span8
        .row
          .span8.conf-block-view
            .conf-block-text
              = @presentation.video_embed.html_safe if @presentation.video_embed.present?
        - if @presentation.file_name.present?
          .row
            .span8.conf-block-view
              .presentation-block-text
                Приложение:
              .presentation-block-text
                = link_to @presentation.file.url do
                  %i.fontello-icon-doc-text-inv.icon-size-16.v-align-top
                  = @presentation.file_name
      .span4.presentation-block-about
        .presentation-block-title
          = @presentation.title
        .presentation-block-text
          = @presentation.content.html_safe
        .presentation-block-text
          %br
          %br
          %br
          Поделиться:
        .blue-block
          %i.fontello-icon-twitter.icon-size-24
          %i.fontello-icon-facebook-rect.icon-size-24
          %i.fontello-icon-vkontakte.icon-size-24
= render :partial => 'layouts/disquss'